options:
  docker: true
definitions:
  services:
    docker:
      memory: 3072
    docker-large:
      memory: 6144
      type: docker
  steps:
    - step: &build-image
        image: node:16
        name: Build Application
        size: 2x
        deployment: test
        script:
          - ssh-keyscan -H $SSH_SERVER >> ~/.ssh/known_hosts
          - ssh -tt $SSH_USER@$SSH_SERVER
          - exit          

clone:
  depth: full
pipelines:
  branches:
    master:
      - step: *build-image
