name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ssh
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deployment/Dockerfile --tag setup:$(date +%s)
    - name: test env
      run: echo "${{ secrets.HOST }}"
